version: 0.0
os: linux

hooks:
  ApplicationStop:
    - location: stopcontainer.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: startcontainer.sh
      timeout: 300
      runas: root