version: 0.2
env:
  parameter-store:
    DOCKER_USERNAME: /docker-credentials/username
    DOCKER_PASSWORD: /docker-credentials/password
    DOCKER_URL: /docker-credentials/url
      
phases:
  install:
    runtime-versions:
      python: 3.11
  pre_build:
    commands:
      - pip install -r requirements.txt
  build:
    commands:
      - echo "Building docker image"
      - echo $DOCKER_PASSWORD |  docker login --username "$DOCKER_USERNAME" --password-stdin
      - docker build --tag "$DOCKER_URL/$DOCKER_USERNAME/flaskapp:latest" .
      - docker push "$DOCKER_URL/$DOCKER_USERNAME/flaskapp:latest"

artifacts:
  files:
    - '**/*'
  base-directory: ../simple-python-app